Bump version to 1.11.1
elastic/opbeans-dotnet pull request #48
Opened 2021-09-13 11:08 UTC by cachedout

This should not be merged [until the 1.11.1 release](https://github.com/elastic/apm-agent-dotnet/releases/tag/untagged-b6742a742f8e28d7864b) is done.

After this is merged, a corresponding tag should be pushed.

2021-09-13 11:12 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fopbeans-dotnet-mbp%2FPR-48/detail/PR-48/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fopbeans-dotnet-mbp%2FPR-48/detail/PR-48/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fopbeans-dotnet-mbp%2FPR-48/detail/PR-48/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fopbeans-dotnet-mbp%2FPR-48/detail/PR-48/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://opbeans-dotnet_48.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2021-09-13T10:58:19.959Z&rangeTo=2021-09-13T11:18:19.959Z&transactionName=apm-agent-dotnet/opbeans-dotnet-mbp/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=e1b649f9f7fac4bc97321b171dd8defc&transactionId=cb5d1a142a9038e3)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-09-13T11:08:19.959+0000


* Duration: 4 min 3 sec


* Commit: a1aa584d7032d3ed2e8d344f96cfc0556f9f7f39




#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/opbeans-dotnet-mbp/job/PR-48/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fopbeans-dotnet-mbp%2FPR-48/detail/PR-48/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Shell Script`
<ul>
<li>Took 0 min 19 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/opbeans-dotnet-mbp/pipelines/PR-48/runs/1/steps/99/log/?start=0">here</a></li>
<li>Description: <code>make build</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-09-13T11:11:34.356Z] 5095cab27771: Pulling fs layer
[2021-09-13T11:11:34.356Z] 3794947fd89f: Pulling fs layer
[2021-09-13T11:11:34.356Z] ead7e401eb0a: Pulling fs layer
[2021-09-13T11:11:34.356Z] bca17eb5dc4d: Pulling fs layer
[2021-09-13T11:11:34.356Z] 3794947fd89f: Waiting
[2021-09-13T11:11:34.356Z] 5095cab27771: Waiting
[2021-09-13T11:11:34.356Z] ead7e401eb0a: Waiting
[2021-09-13T11:11:34.356Z] bca17eb5dc4d: Waiting
[2021-09-13T11:11:34.929Z] c1c8f1c77d66: Verifying Checksum
[2021-09-13T11:11:34.929Z] c1c8f1c77d66: Download complete
[2021-09-13T11:11:34.929Z] 82e5f66f5d0e: Verifying Checksum
[2021-09-13T11:11:34.929Z] 82e5f66f5d0e: Download complete
[2021-09-13T11:11:35.503Z] 3794947fd89f: Verifying Checksum
[2021-09-13T11:11:35.503Z] 3794947fd89f: Download complete
[2021-09-13T11:11:35.503Z] 8f04e8168e38: Verifying Checksum
[2021-09-13T11:11:35.503Z] 8f04e8168e38: Download complete
[2021-09-13T11:11:36.074Z] 5095cab27771: Verifying Checksum
[2021-09-13T11:11:36.074Z] 5095cab27771: Download complete
[2021-09-13T11:11:36.074Z] bca17eb5dc4d: Verifying Checksum
[2021-09-13T11:11:36.074Z] bca17eb5dc4d: Download complete
[2021-09-13T11:11:37.992Z] 8f04e8168e38: Pull complete
[2021-09-13T11:11:37.992Z] ead7e401eb0a: Verifying Checksum
[2021-09-13T11:11:37.992Z] ead7e401eb0a: Download complete
[2021-09-13T11:11:37.992Z] 82e5f66f5d0e: Pull complete
[2021-09-13T11:11:38.254Z] c1c8f1c77d66: Pull complete
[2021-09-13T11:11:40.807Z] 5095cab27771: Pull complete
[2021-09-13T11:11:40.807Z] 3794947fd89f: Pull complete
[2021-09-13T11:11:44.110Z] ead7e401eb0a: Pull complete
[2021-09-13T11:11:44.369Z] bca17eb5dc4d: Pull complete
[2021-09-13T11:11:44.369Z] Digest: sha256:d3e82b2b2c34cdd6b55d872be406981550e1eef1d79889b41a5202bc138a65e6
[2021-09-13T11:11:44.369Z] Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1
[2021-09-13T11:11:44.369Z]  ---> 2db4225db489
[2021-09-13T11:11:44.369Z] Step 2/12 : COPY . /src/
[2021-09-13T11:11:47.670Z]  ---> 6cfc7c0be47a
[2021-09-13T11:11:47.670Z] Step 3/12 : WORKDIR /src
[2021-09-13T11:11:47.670Z]  ---> Running in dbd42c77c11e
[2021-09-13T11:11:47.932Z] Removing intermediate container dbd42c77c11e
[2021-09-13T11:11:47.932Z]  ---> 2ccf5fbc0ce7
[2021-09-13T11:11:47.932Z] Step 4/12 : RUN dotnet restore
[2021-09-13T11:11:47.932Z]  ---> Running in 2a5daec137dc
[2021-09-13T11:11:49.317Z]   Determining projects to restore...
[2021-09-13T11:11:52.619Z] /src/opbeans-dotnet/opbeans-dotnet.csproj : error NU1102: Unable to find package Elastic.Apm.NetCoreAll with version (>= 1.11.1) [/src/opbeans-dotnet.sln]
[2021-09-13T11:11:52.619Z] /src/opbeans-dotnet/opbeans-dotnet.csproj : error NU1102:   - Found 20 version(s) in nuget.org [ Nearest version: 1.11.0 ] [/src/opbeans-dotnet.sln]
[2021-09-13T11:11:52.619Z]   Failed to restore /src/opbeans-dotnet/opbeans-dotnet.csproj (in 2.72 sec).
[2021-09-13T11:11:52.880Z] The command '/bin/sh -c dotnet restore' returned a non-zero code: 1
[2021-09-13T11:11:52.880Z] Makefile:15: recipe for target 'build' failed
[2021-09-13T11:11:52.880Z] make: *** [build] Error 1
[2021-09-13T11:11:53.981Z] Post stage
[2021-09-13T11:11:54.000Z] Running in /var/lib/jenkins/workspace/_dotnet_opbeans-dotnet-mbp_PR-48/src/github.com/elastic
[2021-09-13T11:11:54.367Z] + docker-compose up --build -d
[2021-09-13T11:11:54.940Z] Creating network "elastic_default" with the default driver
[2021-09-13T11:11:55.202Z] Creating volume "elastic_esdata" with local driver
[2021-09-13T11:11:55.202Z] Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:7.3.0)...
[2021-09-13T11:11:55.774Z] 7.3.0: Pulling from elasticsearch/elasticsearch
[2021-09-13T11:12:08.017Z] Digest: sha256:8c7075b17918a954e34d71ab1661ea14737429426376d045a23e79c3632346ab
[2021-09-13T11:12:08.017Z] Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:7.3.0
[2021-09-13T11:12:08.017Z] Pulling apm-server (docker.elastic.co/apm/apm-server:7.3.0)...
[2021-09-13T11:12:08.017Z] 7.3.0: Pulling from apm/apm-server
[2021-09-13T11:12:08.960Z] Digest: sha256:c304773d1e6a123d0b4bceabfc6f47d7a9903da5d2e2b79027e550b37f99266c
[2021-09-13T11:12:08.960Z] Status: Downloaded newer image for docker.elastic.co/apm/apm-server:7.3.0
[2021-09-13T11:12:08.960Z] Building opbeans-dotnet
[2021-09-13T11:12:08.960Z] Step 1/12 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
[2021-09-13T11:12:08.960Z]  ---> 2db4225db489
[2021-09-13T11:12:08.960Z] Step 2/12 : COPY . /src/
[2021-09-13T11:12:14.257Z]  ---> bf7dde0287da
[2021-09-13T11:12:14.257Z] Step 3/12 : WORKDIR /src
[2021-09-13T11:12:14.257Z]  ---> Running in f68831908f40
[2021-09-13T11:12:14.257Z] Removing intermediate container f68831908f40
[2021-09-13T11:12:14.257Z]  ---> 9749ebc3bf8b
[2021-09-13T11:12:14.257Z] Step 4/12 : RUN dotnet restore
[2021-09-13T11:12:14.257Z]  ---> Running in 7d5a4ccad933
[2021-09-13T11:12:14.829Z]   Determining projects to restore...
[2021-09-13T11:12:18.138Z] /src/opbeans-dotnet/opbeans-dotnet.csproj : error NU1102: Unable to find package Elastic.Apm.NetCoreAll with version (>= 1.11.1) [/src/opbeans-dotnet.sln]
[2021-09-13T11:12:18.138Z] /src/opbeans-dotnet/opbeans-dotnet.csproj : error NU1102:   - Found 20 version(s) in nuget.org [ Nearest version: 1.11.0 ] [/src/opbeans-dotnet.sln]
[2021-09-13T11:12:18.138Z]   Failed to restore /src/opbeans-dotnet/opbeans-dotnet.csproj (in [...]

2021-09-13 13:08 UTC, kuisathaverat approved these changes

2021-09-13 13:10 UTC, kuisathaverat commented
the build is broken for that version.

```
13:12:14  Step 4/12 : RUN dotnet restore
13:12:14   ---> Running in 7d5a4ccad933
13:12:14    Determining projects to restore...
13:12:18  /src/opbeans-dotnet/opbeans-dotnet.csproj : error NU1102: Unable to find package Elastic.Apm.NetCoreAll with version (>= 1.11.1) [/src/opbeans-dotnet.sln]
13:12:18  /src/opbeans-dotnet/opbeans-dotnet.csproj : error NU1102:   - Found 20 version(s) in nuget.org [ Nearest version: 1.11.0 ] [/src/opbeans-dotnet.sln]
13:12:18    Failed to restore /src/opbeans-dotnet/opbeans-dotnet.csproj (in 3.04 sec).
```

2021-09-13 13:10 UTC, kuisathaverat requested changes
CI do not pass

2021-09-13 13:23 UTC, cachedout commented
> CI do not pass

CI didn't pass because, [as I mentioned in the description](https://github.com/elastic/opbeans-dotnet/pull/48#issue-732634787), this PR was submitted prior to the release of 1.11.1.

2021-09-13 13:53 UTC, cachedout commented
@v1v Thanks for the info. I loosed the regex a bit here: https://github.com/elastic/apm-agent-dotnet/pull/1489

Regardless of that, it seems like we should still re-rerun the tests on this and merge it since we want to get the opbean updated to 1.11.1. WDYT?

2021-09-13 15:48 UTC, v1v commented
Ideally [build-1.11.1](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/1.11.1/1/) should be the one driving these kind of changes. 

Let's see if it gets green and the stage for the opbeans bump happens

2021-09-14 08:18 UTC, v1v commented
> Ideally build-1.11.1 should be the one driving these kind of changes.


It failed :/ with some test failures. So automation won't work at the moment

2021-09-14 08:19 UTC, v1v approved these changes

2021-09-14 08:29 UTC, merged